services:
  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    container_name: starlab-backend
    image: starlab-backend:latest
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgres://lab:lab1234@pgvector:5432/starlabdb
      - PORT=5001
      - NODE_ENV=production
    volumes:
      - ./apps/backend/dist:/app/apps/backend/dist
      - ./apps/backend/prisma:/app/apps/backend/prisma
      - ./packages/shared:/app/packages/shared
      - ./apps/backend/node_modules/.prisma:/app/apps/backend/node_modules/.prisma
    restart: unless-stopped

networks:
  default:
    driver: bridge
    name: orignx-network
