services:
  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    container_name: starlab-backend
    image: starlab-backend:latest
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgres://lab:lab1234@postgresql:5432/starlabdb
      - PORT=5001
      - NODE_ENV=production
    depends_on:
      - postgresql
    restart: unless-stopped

  postgresql:
    image: postgres:13
    environment:
      POSTGRES_USER: lab
      POSTGRES_PASSWORD: lab1234
      POSTGRES_DB: starlabdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: # Define the postgres data volume
networks:
  default:
    driver: bridge
    name: orignx-network
