services:
  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    container_name: starlab-backend
    image: starlab-backend:latest
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgres://lab:lab1234@pgvector:5432/starlabdb
      - PORT=5001
      - NODE_ENV=production
    volumes:
      - ./apps/backend/uploads:/app/apps/backend/uploads
    restart: unless-stopped
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: ./apps/frontend/Dockerfile
  #   container_name: starlab-frontend
  #   image: starlab-frontend:latest
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./apps/frontend:/app/apps/frontend
  #     - ./packages/shared:/app/packages/shared
  # pgvector:
  #   image: postgres:15
  #   container_name: starlab-postgres
  #   environment:
  #     - POSTGRES_USER=lab
  #     - POSTGRES_PASSWORD=lab1234
  #     - POSTGRES_DB=starlabdb
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   restart: unless-stopped
networks:
  default:
    driver: bridge
    name: orignx-network

# volumes:
#   pgdata:
